import React,{useEffect,useState} from 'react'; import{createRoot}from'react-dom/client'; import{Activity,AlertTriangle,CheckCircle2,Clock3,Play,ShieldCheck}from'lucide-react'; import'./styles.css';
type Incident={id:string,title:string,service:string,environment:string,severity:string,scenario:string,status:string,hypothesis?:string,confidence?:number,recommendation?:string,proposed_action?:Record<string,unknown>,tool_call_count:number,accumulated_cost:number}; type Event={id:number,sequence:number,event_type:string,actor:string,payload:Record<string,unknown>,created_at:string};
const api='/api',badge=(s:string)=>s.replaceAll('_',' ');
function App(){const[items,setItems]=useState<Incident[]>([]),[selected,setSelected]=useState<Incident|null>(null),[events,setEvents]=useState<Event[]>([]),[busy,setBusy]=useState(false);
 const load=async(id?:string)=>{const all=await fetch(`${api}/incidents`).then(r=>r.json());setItems(all);const target=id?all.find((x:Incident)=>x.id===id):selected&&all.find((x:Incident)=>x.id===selected.id);if(target){setSelected(target);setEvents(await fetch(`${api}/incidents/${target.id}/events`).then(r=>r.json()))}};useEffect(()=>{load()},[]);
 const create=async(scenario:string)=>{setBusy(true);const x=await fetch(`${api}/incidents`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`${badge(scenario)} detected`,service:'checkout-api',environment:'production',severity:'SEV1',scenario})}).then(r=>r.json());await load(x.id);setBusy(false)};
 const act=async(path:string,body?:unknown)=>{if(!selected)return;setBusy(true);await fetch(`${api}/incidents/${selected.id}/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});await load(selected.id);setBusy(false)};
 return <main><header><div className="brand"><ShieldCheck/><div><h1>Ops Sentinel</h1><p>Controlled incident investigation</p></div></div><span className="live"><i/> LOCAL SIMULATION</span></header>
 <section className="hero"><div><span className="eyebrow">RELIABLE TOOL-USING OPERATIONS AGENT</span><h2>Investigate with evidence.<br/><em>Act only with approval.</em></h2><p>Every tool call, hypothesis, decision, and state change is typed, policy-checked, and preserved.</p></div><div className="metrics"><article><Activity/><b>{items.length}</b><span>Incidents</span></article><article><Clock3/><b>{selected?.tool_call_count||0}</b><span>Tool calls</span></article><article><ShieldCheck/><b>0</b><span>Unsafe actions</span></article></div></section>
 <section className="scenario"><span>LAUNCH SIMULATION</span>{['bad_deployment','db_exhaustion','dependency_outage','prompt_injection'].map(s=><button disabled={busy} onClick={()=>create(s)} key={s}>+ {badge(s)}</button>)}</section>
 <div className="grid"><aside><div className="panel-title"><span>INCIDENT QUEUE</span><b>{items.length}</b></div>{items.length===0&&<p className="empty">Launch a simulation to begin.</p>}{items.map(x=><button className={`incident ${selected?.id===x.id?'active':''}`} onClick={()=>{setSelected(x);fetch(`${api}/incidents/${x.id}/events`).then(r=>r.json()).then(setEvents)}} key={x.id}><div><AlertTriangle/><strong>{x.title}</strong></div><small>{x.service} · {x.severity}</small><span className={`status ${x.status}`}>{badge(x.status)}</span></button>)}</aside>
 <section className="workspace">{!selected?<div className="blank"><ShieldCheck/><h3>No incident selected</h3><p>Create or select an incident to inspect its execution trace.</p></div>:<><div className="summary"><div><span className="eyebrow">{selected.id.slice(0,8)} · {selected.environment}</span><h3>{selected.title}</h3><p>{selected.service}</p></div><span className={`status ${selected.status}`}>{badge(selected.status)}</span></div>
 <div className="cards"><article><label>ROOT-CAUSE HYPOTHESIS</label><p>{selected.hypothesis||'Waiting for investigation.'}</p>{selected.confidence&&<div className="confidence"><i style={{width:`${selected.confidence*100}%`}}/><span>{Math.round(selected.confidence*100)}% confidence</span></div>}</article><article><label>RECOMMENDATION</label><p>{selected.recommendation||'No recommendation yet.'}</p></article></div>
 <div className="actions">{selected.status==='alert_received'&&<button className="primary" disabled={busy} onClick={()=>act('investigate')}><Play/>Investigate incident</button>}{selected.status==='awaiting_approval'&&<><div className="approval"><ShieldCheck/><div><b>Human approval required</b><small>{JSON.stringify(selected.proposed_action)}</small></div></div><button className="approve" onClick={()=>act('approval',{decision:'approved',approver:'local-oncall'})}>Approve action</button><button className="reject" onClick={()=>act('approval',{decision:'rejected',approver:'local-oncall'})}>Reject</button></>}</div>
 <div className="timeline"><div className="panel-title"><span>EXECUTION TRACE</span><b>{events.length} events</b></div>{events.map(e=><div className="event" key={e.id}><div className="dot">{e.event_type.includes('verified')||e.event_type.includes('succeeded')?<CheckCircle2/>:<Activity/>}</div><div><b>{badge(e.event_type)}</b><small>{e.actor} · {new Date(e.created_at).toLocaleTimeString()}</small><pre>{JSON.stringify(e.payload,null,2)}</pre></div></div>)}</div></>}</section></div></main>}
createRoot(document.getElementById('root')!).render(<App/>);
